// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("TalBot.PluginsCSharp")]
[assembly: AssemblyProductAttribute("TalBot")]
[assembly: AssemblyDescriptionAttribute("A bot for posting status messages to Slack and responding to Slack posts.")]
[assembly: AssemblyVersionAttribute("0.0.3")]
[assembly: AssemblyFileVersionAttribute("0.0.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.3";
    }
}
